eureka :
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/


spring:
  application:
     name: Activity_Service

  security:
    user:
      name: mabrouka
      password: annabi
  datasource:
    url: jdbc:postgresql://localhost:5432/Activity
    username: postgres
    password: insy2s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  management:
    endpoints:
    web:
      exposure:
        include: "*"
        spring:
          config:
             import: optional:configserver:http://localhost:8888
  port: 8084
  
  user:
    url: http://localhost:8090/api/auth
  



