
spring:
  application:
    name: AddressService

  # Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adress_db
    username: postgres

    password: 123



  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : true
    properties:
      hibernate:
        format_sql: true
#  Server configuration
server:
  port: 8083
eureka :
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/

message: From User Service 123